import { useState } from 'react'
import type { AgentLensClientModel } from '../client/model'
import { useClientSnapshot } from '../App'
import { AgentScope, agentLabel, sourceDot } from '../components/AgentScope'

const capabilityLabel:Record<string,string>={'session':'Session','transcript':'对话记录','tool-call':'工具调用','tool-result':'工具结果','permission':'权限','subagent':'Subagent','context':'上下文','thinking':'Thinking','asset-discovery':'资产发现','asset-invocation':'资产调用','artifact-action':'产物操作','usage':'Usage'}

export function AgentsPage({model}:{model:AgentLensClientModel}){
 const snapshot=useClientSnapshot(model),agents=snapshot.facets?.agents??[],items=snapshot.agents?.items??[]; const [sourceId,setSourceId]=useState('')
 const shown=sourceId?items.filter(item=>item.sourceId===sourceId):items
 return <main className="mx-auto max-w-[1800px]"><div className="toolbar"><AgentScope agents={agents} value={sourceId} onChange={setSourceId}/><button className="icon-button ml-auto" onClick={()=>void model.refreshFacetsAndAgents()} title="重新扫描视图">↻</button></div><div className="p-6"><div className="mb-6"><h1 className="text-xl font-semibold">Agent 概览</h1><p className="mt-1 text-sm text-muted">看清本机 Agent 的检测状态、安装信息、可观测能力与实际使用资产。</p></div><div className="grid gap-5 xl:grid-cols-2">{shown.map(agent=><article key={agent.sourceId} className="rounded-xl border border-line bg-surface p-5"><div className="flex items-start gap-3"><span className={`mt-1 size-2.5 rounded-full ${sourceDot(agent.sourceId)}`}/><div><h2 className="font-semibold">{agentLabel(agent.sourceId,agent.displayName)}</h2><div className="mt-1 text-xs text-muted">{agent.detected?'已检测':'未检测'} · Source 已启用</div></div><span className={`ml-auto rounded-full px-2 py-1 text-xs ${agent.detected?'bg-success/10 text-success':'bg-soft text-muted'}`}>{agent.detected?'Detected':'Not found'}</span></div>
  <section className="mt-5"><h3 className="section-label">安装</h3>{agent.installations.length?agent.installations.map(item=><div key={item.id} className="mb-2 rounded-lg bg-soft p-3 text-xs"><div className="font-medium">{item.version??'版本未知'}</div>{item.executable&&<div className="mt-1 break-all text-muted">Executable · {item.executable}</div>}{item.configRoot&&<div className="mt-1 break-all text-muted">Config · {item.configRoot}</div>}{item.dataRoot&&<div className="mt-1 break-all text-muted">Data · {item.dataRoot}</div>}</div>):<div className="text-sm text-muted">尚未发现本机安装</div>}</section>
  <section className="mt-5"><h3 className="section-label">可观测能力</h3><div className="flex flex-wrap gap-2">{agent.capabilities.map(cap=><span key={cap.name} title={cap.reason} className={`rounded-md border px-2 py-1 text-xs ${cap.status==='available'?'border-success/30 bg-success/10 text-success':cap.status==='partial'||cap.status==='experimental'?'border-warning/30 bg-warning/10 text-warning':'border-line text-muted'}`}>{capabilityLabel[cap.name]??cap.name} · {cap.status}</span>)}</div></section>
  <section className="mt-5"><div className="flex items-center justify-between"><h3 className="section-label">实际使用资产</h3><span className="text-[11px] text-muted">usage-only</span></div>{agent.usedAssets.length?<div className="space-y-2">{agent.usedAssets.map(asset=><div key={`${asset.type}:${asset.canonicalName}`} className="flex items-center rounded-lg border border-line px-3 py-2 text-sm"><span className="font-medium">{asset.canonicalName}</span><span className="ml-2 text-xs text-muted">{asset.type.toUpperCase()}</span><span className="ml-auto text-xs text-muted">{asset.callCount} 次</span></div>)}</div>:<div className="text-sm text-muted">暂无可可靠归因的 Skill / MCP 使用记录</div>}<p className="mt-2 text-xs text-muted">这里目前只表示“实际使用过”，不冒充“已安装 / 已配置”。完整资产库存将在资产状态查询接通后展示。</p></section>
 </article>)}</div>{!shown.length&&<div className="empty py-24">没有可显示的 Agent</div>}</div></main>
}
